{"created": 1649332755.620113, "duration": 4.367422580718994, "exitcode": 1, "root": "C:\\Users\\Coke\\playground\\Section3\\ds-sa-nosql", "environment": {"Python": "3.8.13", "Platform": "Windows-10-10.0.19043-SP0", "Packages": {"pytest": "6.2.2", "py": "1.10.0", "pluggy": "0.13.1"}, "Plugins": {"json-report": "1.5.0", "metadata": "2.0.1", "submit": "1.3.3"}}, "summary": {"passed": 2, "failed": 8, "error": 3, "total": 13, "collected": 13}, "collectors": [{"nodeid": "", "outcome": "passed", "result": [{"nodeid": "tests/conftest.py", "type": "Module"}, {"nodeid": "tests/Part_1/__init__.py", "type": "Package"}, {"nodeid": "tests/Part_2/__init__.py", "type": "Package"}, {"nodeid": "tests/Part_3/__init__.py", "type": "Package"}, {"nodeid": "tests/Part_4/__init__.py", "type": "Package"}, {"nodeid": "tests/Part_5/__init__.py", "type": "Package"}]}, {"nodeid": "tests/conftest.py", "outcome": "passed", "result": []}, {"nodeid": "tests/Part_1/__init__.py", "outcome": "passed", "result": []}, {"nodeid": "tests/Part_1/Part_1.py", "outcome": "passed", "result": [{"nodeid": "tests/Part_1/Part_1.py::test_openweather", "type": "Function", "lineno": 2}]}, {"nodeid": "tests/Part_1/conftest.py", "outcome": "passed", "result": []}, {"nodeid": "tests/Part_1/__init__.py", "outcome": "passed", "result": [{"nodeid": "tests/Part_1/__init__.py", "type": "Module"}, {"nodeid": "tests/Part_1/Part_1.py", "type": "Module"}, {"nodeid": "tests/Part_1/conftest.py", "type": "Module"}]}, {"nodeid": "tests/Part_2/__init__.py", "outcome": "passed", "result": []}, {"nodeid": "tests/Part_2/Part_2.py", "outcome": "passed", "result": [{"nodeid": "tests/Part_2/Part_2.py::test_octokit", "type": "Function", "lineno": 2}]}, {"nodeid": "tests/Part_2/conftest.py", "outcome": "passed", "result": []}, {"nodeid": "tests/Part_2/__init__.py", "outcome": "passed", "result": [{"nodeid": "tests/Part_2/__init__.py", "type": "Module"}, {"nodeid": "tests/Part_2/Part_2.py", "type": "Module"}, {"nodeid": "tests/Part_2/conftest.py", "type": "Module"}]}, {"nodeid": "tests/Part_3/__init__.py", "outcome": "passed", "result": []}, {"nodeid": "tests/Part_3/Part_3.py", "outcome": "passed", "result": [{"nodeid": "tests/Part_3/Part_3.py::test_octokit_names", "type": "Function", "lineno": 4}]}, {"nodeid": "tests/Part_3/conftest.py", "outcome": "passed", "result": []}, {"nodeid": "tests/Part_3/__init__.py", "outcome": "passed", "result": [{"nodeid": "tests/Part_3/__init__.py", "type": "Module"}, {"nodeid": "tests/Part_3/Part_3.py", "type": "Module"}, {"nodeid": "tests/Part_3/conftest.py", "type": "Module"}]}, {"nodeid": "tests/Part_4/__init__.py", "outcome": "passed", "result": []}, {"nodeid": "tests/Part_4/Part_4.py", "outcome": "passed", "result": [{"nodeid": "tests/Part_4/Part_4.py::test_mongodb_table_collection_id", "type": "Function", "lineno": 5}, {"nodeid": "tests/Part_4/Part_4.py::test_sqlite_exist", "type": "Function", "lineno": 21}, {"nodeid": "tests/Part_4/Part_4.py::test_sqlite_user_table_schema", "type": "Function", "lineno": 27}, {"nodeid": "tests/Part_4/Part_4.py::test_sqlite_label_table_schema", "type": "Function", "lineno": 42}, {"nodeid": "tests/Part_4/Part_4.py::test_sqlite_prlist_table_schema", "type": "Function", "lineno": 58}, {"nodeid": "tests/Part_4/Part_4.py::test_sqlite_user_data", "type": "Function", "lineno": 78}, {"nodeid": "tests/Part_4/Part_4.py::test_sqlite_label_data", "type": "Function", "lineno": 90}, {"nodeid": "tests/Part_4/Part_4.py::test_sqlite_prlist_data", "type": "Function", "lineno": 102}]}, {"nodeid": "tests/Part_4/conftest.py", "outcome": "passed", "result": []}, {"nodeid": "tests/Part_4/__init__.py", "outcome": "passed", "result": [{"nodeid": "tests/Part_4/__init__.py", "type": "Module"}, {"nodeid": "tests/Part_4/Part_4.py", "type": "Module"}, {"nodeid": "tests/Part_4/conftest.py", "type": "Module"}]}, {"nodeid": "tests/Part_5/__init__.py", "outcome": "passed", "result": []}, {"nodeid": "tests/Part_5/Part_5.py", "outcome": "passed", "result": [{"nodeid": "tests/Part_5/Part_5.py::test_collection", "type": "Function", "lineno": 3}, {"nodeid": "tests/Part_5/Part_5.py::test_data_format", "type": "Function", "lineno": 17}]}, {"nodeid": "tests/Part_5/conftest.py", "outcome": "passed", "result": []}, {"nodeid": "tests/Part_5/__init__.py", "outcome": "passed", "result": [{"nodeid": "tests/Part_5/__init__.py", "type": "Module"}, {"nodeid": "tests/Part_5/Part_5.py", "type": "Module"}, {"nodeid": "tests/Part_5/conftest.py", "type": "Module"}]}], "tests": [{"nodeid": "tests/Part_1/Part_1.py::test_openweather", "lineno": 2, "outcome": "passed", "keywords": ["Part_1.py", "test_openweather", "ds-sa-nosql", "tests/Part_1/__init__.py"], "setup": {"duration": 0.04807519999999954, "outcome": "passed"}, "call": {"duration": 0.11041640000000008, "outcome": "passed"}, "teardown": {"duration": 0.009252299999999991, "outcome": "passed"}}, {"nodeid": "tests/Part_2/Part_2.py::test_octokit", "lineno": 2, "outcome": "passed", "keywords": ["Part_2.py", "test_octokit", "tests/Part_2/__init__.py", "ds-sa-nosql"], "setup": {"duration": 0.06011420000000012, "outcome": "passed"}, "call": {"duration": 0.4350163, "outcome": "passed"}, "teardown": {"duration": 0.010306599999999833, "outcome": "passed"}}, {"nodeid": "tests/Part_3/Part_3.py::test_octokit_names", "lineno": 4, "outcome": "failed", "keywords": ["Part_3.py", "tests/Part_3/__init__.py", "test_octokit_names", "ds-sa-nosql"], "setup": {"duration": 0.0010612999999999317, "outcome": "passed"}, "call": {"duration": 0.00043330000000008084, "outcome": "failed", "crash": {"path": "C:\\Users\\Coke\\playground\\Section3\\ds-sa-nosql\\tests\\Part_3\\Part_3.py", "lineno": 10, "message": "AssertionError: assert None == {'.github', '...-app.js', ...}\n  +None\n  -{'auth-basic.js', 'graphql-schema', 'auth-app.js', 'endpoint.js', 'handbook', 'create-octokit-project.js', 'app.js', 'oauth-app.js', 'auth-callback.js', 'auth-token.js', 'graphql-action', '.github', 'auth-oauth-user.js', 'oauth-authorization-url.js', 'auth-oauth-app.js', 'auth-oauth-device.js', 'auth-unauthenticated.js', 'octokit-next.js', 'graphql.js', 'oauth-methods.js', 'discussions', 'go-octokit', 'fixtures-server', 'auth-action.js', 'action.js', 'app-permissions', 'core.js', 'auth-oauth-user-client.js', 'fixtures', 'authentication-strategies.js'}"}, "traceback": [{"path": "tests\\Part_3\\Part_3.py", "lineno": 10, "message": "AssertionError"}], "longrepr": "def test_octokit_names():\n        \"\"\"\n        octokit \uc774\ub780 \uc18c\uc720\uc790\uc758 repo \ubaa9\ub85d\uc744 \ub370\uc774\ud130\ubca0\uc774\uc2a4\uc5d0 \uc785\ub825\ud588\ub294\uc9c0 \ud655\uc778\ud569\ub2c8\ub2e4.\n        \"\"\"\n        repo_names = {repo['name'] for repo in dont_touch}\n>       assert Part_3_answer() == repo_names\nE       AssertionError: assert None == {'.github', '...-app.js', ...}\nE         +None\nE         -{'auth-basic.js', 'graphql-schema', 'auth-app.js', 'endpoint.js', 'handbook', 'create-octokit-project.js', 'app.js', 'oauth-app.js', 'auth-callback.js', 'auth-token.js', 'graphql-action', '.github', 'auth-oauth-user.js', 'oauth-authorization-url.js', 'auth-oauth-app.js', 'auth-oauth-device.js', 'auth-unauthenticated.js', 'octokit-next.js', 'graphql.js', 'oauth-methods.js', 'discussions', 'go-octokit', 'fixtures-server', 'auth-action.js', 'action.js', 'app-permissions', 'core.js', 'auth-oauth-user-client.js', 'fixtures', 'authentication-strategies.js'}\n\ntests\\Part_3\\Part_3.py:10: AssertionError"}, "teardown": {"duration": 0.00035939999999978767, "outcome": "passed"}}, {"nodeid": "tests/Part_4/Part_4.py::test_mongodb_table_collection_id", "lineno": 5, "outcome": "error", "keywords": ["Part_4.py", "tests/Part_4/__init__.py", "test_mongodb_table_collection_id", "ds-sa-nosql"], "setup": {"duration": 0.0010083999999999094, "outcome": "failed", "crash": {"path": "C:\\Users\\Coke\\anaconda3\\envs\\s2n4\\lib\\site-packages\\pymongo\\uri_parser.py", "lineno": 65, "message": "pymongo.errors.InvalidURI: The empty string is not valid username."}, "traceback": [{"path": "tests\\Part_4\\conftest.py", "lineno": 7, "message": ""}, {"path": "..\\..\\..\\anaconda3\\envs\\s2n4\\lib\\site-packages\\pymongo\\mongo_client.py", "lineno": 639, "message": "in __init__"}, {"path": "..\\..\\..\\anaconda3\\envs\\s2n4\\lib\\site-packages\\pymongo\\uri_parser.py", "lineno": 470, "message": "in parse_uri"}, {"path": "..\\..\\..\\anaconda3\\envs\\s2n4\\lib\\site-packages\\pymongo\\uri_parser.py", "lineno": 65, "message": "InvalidURI"}], "longrepr": "@pytest.fixture(scope='module')\n    def connection():\n>       conn = MongoClient(MONGO_URI)\n\ntests\\Part_4\\conftest.py:7: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\..\\..\\anaconda3\\envs\\s2n4\\lib\\site-packages\\pymongo\\mongo_client.py:639: in __init__\n    res = uri_parser.parse_uri(\n..\\..\\..\\anaconda3\\envs\\s2n4\\lib\\site-packages\\pymongo\\uri_parser.py:470: in parse_uri\n    user, passwd = parse_userinfo(userinfo)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nuserinfo = ':'\n\n    def parse_userinfo(userinfo):\n        \"\"\"Validates the format of user information in a MongoDB URI.\n        Reserved characters like ':', '/', '+' and '@' must be escaped\n        following RFC 3986.\n    \n        Returns a 2-tuple containing the unescaped username followed\n        by the unescaped password.\n    \n        :Paramaters:\n            - `userinfo`: A string of the form <username>:<password>\n    \n        .. versionchanged:: 2.2\n           Now uses `urllib.unquote_plus` so `+` characters must be escaped.\n        \"\"\"\n        if '@' in userinfo or userinfo.count(':') > 1:\n            if PY3:\n                quote_fn = \"urllib.parse.quote_plus\"\n            else:\n                quote_fn = \"urllib.quote_plus\"\n            raise InvalidURI(\"Username and password must be escaped according to \"\n                             \"RFC 3986, use %s().\" % quote_fn)\n        user, _, passwd = userinfo.partition(\":\")\n        # No password is expected with GSSAPI authentication.\n        if not user:\n>           raise InvalidURI(\"The empty string is not valid username.\")\nE           pymongo.errors.InvalidURI: The empty string is not valid username.\n\n..\\..\\..\\anaconda3\\envs\\s2n4\\lib\\site-packages\\pymongo\\uri_parser.py:65: InvalidURI"}, "teardown": {"duration": 0.00033729999999998483, "outcome": "passed"}}, {"nodeid": "tests/Part_4/Part_4.py::test_sqlite_exist", "lineno": 21, "outcome": "failed", "keywords": ["Part_4.py", "test_sqlite_exist", "ds-sa-nosql", "tests/Part_4/__init__.py"], "setup": {"duration": 0.0002611999999997394, "outcome": "passed"}, "call": {"duration": 0.0002766000000002933, "outcome": "failed", "crash": {"path": "C:\\Users\\Coke\\playground\\Section3\\ds-sa-nosql\\tests\\Part_4\\Part_4.py", "lineno": 26, "message": "assert False"}, "traceback": [{"path": "tests\\Part_4\\Part_4.py", "lineno": 26, "message": "AssertionError"}], "longrepr": "def test_sqlite_exist():\n        \"\"\"\n        SQLite \ub370\uc774\ud130\ubca0\uc774\uc2a4\uac00 \uc874\uc7ac\ud558\ub294\uc9c0 \ud655\uc778\ud569\ub2c8\ub2e4.\n        \"\"\"\n>       assert table_exist\nE       assert False\n\ntests\\Part_4\\Part_4.py:26: AssertionError"}, "teardown": {"duration": 0.00025480000000044356, "outcome": "passed"}}, {"nodeid": "tests/Part_4/Part_4.py::test_sqlite_user_table_schema", "lineno": 27, "outcome": "failed", "keywords": ["Part_4.py", "tests/Part_4/__init__.py", "ds-sa-nosql", "test_sqlite_user_table_schema"], "setup": {"duration": 0.00021830000000022665, "outcome": "passed"}, "call": {"duration": 0.0002301999999998472, "outcome": "failed", "crash": {"path": "C:\\Users\\Coke\\playground\\Section3\\ds-sa-nosql\\tests\\Part_4\\Part_4.py", "lineno": 37, "message": "AttributeError: 'NoneType' object has no attribute 'cursor'"}, "traceback": [{"path": "tests\\Part_4\\Part_4.py", "lineno": 37, "message": "AttributeError"}], "longrepr": "def test_sqlite_user_table_schema():\n        \"\"\"\n        User \ud14c\uc774\ube14\uc758 \uc2a4\ud0a4\ub9c8\uac00 \uc815\ud655\ud55c\uc9c0 \ud655\uc778\ud569\ub2c8\ub2e4.\n        \"\"\"\n        fields = {\n            ('id','INTEGER', 1, 1),\n            ('login','VARCHAR(10)', 0, 0),\n            ('node_id','VARCHAR(20)', 0, 0)\n        }\n>       cursor = conn.cursor()\nE       AttributeError: 'NoneType' object has no attribute 'cursor'\n\ntests\\Part_4\\Part_4.py:37: AttributeError"}, "teardown": {"duration": 0.00023580000000045231, "outcome": "passed"}}, {"nodeid": "tests/Part_4/Part_4.py::test_sqlite_label_table_schema", "lineno": 42, "outcome": "failed", "keywords": ["test_sqlite_label_table_schema", "tests/Part_4/__init__.py", "ds-sa-nosql", "Part_4.py"], "setup": {"duration": 0.00033840000000040504, "outcome": "passed"}, "call": {"duration": 0.0002865999999999147, "outcome": "failed", "crash": {"path": "C:\\Users\\Coke\\playground\\Section3\\ds-sa-nosql\\tests\\Part_4\\Part_4.py", "lineno": 53, "message": "AttributeError: 'NoneType' object has no attribute 'cursor'"}, "traceback": [{"path": "tests\\Part_4\\Part_4.py", "lineno": 53, "message": "AttributeError"}], "longrepr": "def test_sqlite_label_table_schema():\n        \"\"\"\n        Label \ud14c\uc774\ube14\uc758 \uc2a4\ud0a4\ub9c8\uac00 \uc815\ud655\ud55c\uc9c0 \ud655\uc778\ud569\ub2c8\ub2e4.\n        \"\"\"\n        fields = {\n            ('id','INTEGER', 1, 1),\n            ('name','VARCHAR(20)', 0, 0),\n            ('node_id','VARCHAR(20)', 0, 0),\n            ('color','VARCHAR(10)', 0, 0)\n        }\n>       cursor = conn.cursor()\nE       AttributeError: 'NoneType' object has no attribute 'cursor'\n\ntests\\Part_4\\Part_4.py:53: AttributeError"}, "teardown": {"duration": 0.00028439999999996246, "outcome": "passed"}}, {"nodeid": "tests/Part_4/Part_4.py::test_sqlite_prlist_table_schema", "lineno": 58, "outcome": "failed", "keywords": ["Part_4.py", "test_sqlite_prlist_table_schema", "ds-sa-nosql", "tests/Part_4/__init__.py"], "setup": {"duration": 0.00021750000000064773, "outcome": "passed"}, "call": {"duration": 0.0003166999999999476, "outcome": "failed", "crash": {"path": "C:\\Users\\Coke\\playground\\Section3\\ds-sa-nosql\\tests\\Part_4\\Part_4.py", "lineno": 73, "message": "AttributeError: 'NoneType' object has no attribute 'cursor'"}, "traceback": [{"path": "tests\\Part_4\\Part_4.py", "lineno": 73, "message": "AttributeError"}], "longrepr": "def test_sqlite_prlist_table_schema():\n        \"\"\"\n        PRlist \ud14c\uc774\ube14\uc758 \uc2a4\ud0a4\ub9c8\uac00 \uc815\ud655\ud55c\uc9c0 \ud655\uc778\ud569\ub2c8\ub2e4.\n        \"\"\"\n        fields = {\n            ('id','INTEGER', 1, 1),\n            ('node_id','VARCHAR(20)', 0, 0),\n            ('title','VARCHAR(100)', 0, 0),\n            ('body','VARCHAR(100)', 0, 0),\n            ('created_at','VARCHAR(20)', 0, 0),\n            ('comments','INTEGER', 0, 0),\n            ('userId','INTEGER', 0, 0),\n            ('labelId','INTEGER', 0, 0)\n        }\n>       cursor = conn.cursor()\nE       AttributeError: 'NoneType' object has no attribute 'cursor'\n\ntests\\Part_4\\Part_4.py:73: AttributeError"}, "teardown": {"duration": 0.00023930000000049745, "outcome": "passed"}}, {"nodeid": "tests/Part_4/Part_4.py::test_sqlite_user_data", "lineno": 78, "outcome": "failed", "keywords": ["test_sqlite_user_data", "Part_4.py", "tests/Part_4/__init__.py", "ds-sa-nosql"], "setup": {"duration": 0.00026809999999954925, "outcome": "passed"}, "call": {"duration": 0.00022669999999980206, "outcome": "failed", "crash": {"path": "C:\\Users\\Coke\\playground\\Section3\\ds-sa-nosql\\tests\\Part_4\\Part_4.py", "lineno": 83, "message": "AttributeError: 'NoneType' object has no attribute 'cursor'"}, "traceback": [{"path": "tests\\Part_4\\Part_4.py", "lineno": 83, "message": "AttributeError"}], "longrepr": "def test_sqlite_user_data():\n        \"\"\"\n        SQLite \ub370\uc774\ud130\ubca0\uc774\uc2a4\uc758 User \ud14c\uc774\ube14 \ub370\uc774\ud130\ub97c \uac80\uc0ac\ud569\ub2c8\ub2e4.\n        \"\"\"\n>       cursor = conn.cursor()\nE       AttributeError: 'NoneType' object has no attribute 'cursor'\n\ntests\\Part_4\\Part_4.py:83: AttributeError"}, "teardown": {"duration": 0.00022350000000059822, "outcome": "passed"}}, {"nodeid": "tests/Part_4/Part_4.py::test_sqlite_label_data", "lineno": 90, "outcome": "failed", "keywords": ["Part_4.py", "tests/Part_4/__init__.py", "test_sqlite_label_data", "ds-sa-nosql"], "setup": {"duration": 0.00021990000000027266, "outcome": "passed"}, "call": {"duration": 0.000222400000000178, "outcome": "failed", "crash": {"path": "C:\\Users\\Coke\\playground\\Section3\\ds-sa-nosql\\tests\\Part_4\\Part_4.py", "lineno": 95, "message": "AttributeError: 'NoneType' object has no attribute 'cursor'"}, "traceback": [{"path": "tests\\Part_4\\Part_4.py", "lineno": 95, "message": "AttributeError"}], "longrepr": "def test_sqlite_label_data():\n        \"\"\"\n        SQLite \ub370\uc774\ud130\ubca0\uc774\uc2a4\uc758 Label \ud14c\uc774\ube14 \ub370\uc774\ud130\ub97c \uac80\uc0ac\ud569\ub2c8\ub2e4.\n        \"\"\"\n>       cursor = conn.cursor()\nE       AttributeError: 'NoneType' object has no attribute 'cursor'\n\ntests\\Part_4\\Part_4.py:95: AttributeError"}, "teardown": {"duration": 0.0002667000000000641, "outcome": "passed"}}, {"nodeid": "tests/Part_4/Part_4.py::test_sqlite_prlist_data", "lineno": 102, "outcome": "failed", "keywords": ["Part_4.py", "tests/Part_4/__init__.py", "test_sqlite_prlist_data", "ds-sa-nosql"], "setup": {"duration": 0.00023480000000031254, "outcome": "passed"}, "call": {"duration": 0.00023109999999970654, "outcome": "failed", "crash": {"path": "C:\\Users\\Coke\\playground\\Section3\\ds-sa-nosql\\tests\\Part_4\\Part_4.py", "lineno": 107, "message": "AttributeError: 'NoneType' object has no attribute 'cursor'"}, "traceback": [{"path": "tests\\Part_4\\Part_4.py", "lineno": 107, "message": "AttributeError"}], "longrepr": "def test_sqlite_prlist_data():\n        \"\"\"\n        SQLite \ub370\uc774\ud130\ubca0\uc774\uc2a4\uc758 issue \ud14c\uc774\ube14 \ub370\uc774\ud130\ub97c \uac80\uc0ac\ud569\ub2c8\ub2e4.\n        \"\"\"\n>       cursor = conn.cursor()\nE       AttributeError: 'NoneType' object has no attribute 'cursor'\n\ntests\\Part_4\\Part_4.py:107: AttributeError"}, "teardown": {"duration": 0.00025920000000034804, "outcome": "passed"}}, {"nodeid": "tests/Part_5/Part_5.py::test_collection", "lineno": 3, "outcome": "error", "keywords": ["Part_5.py", "test_collection", "tests/Part_5/__init__.py", "ds-sa-nosql"], "setup": {"duration": 0.0009679000000000215, "outcome": "failed", "crash": {"path": "C:\\Users\\Coke\\anaconda3\\envs\\s2n4\\lib\\site-packages\\pymongo\\uri_parser.py", "lineno": 65, "message": "pymongo.errors.InvalidURI: The empty string is not valid username."}, "traceback": [{"path": "tests\\Part_5\\conftest.py", "lineno": 7, "message": ""}, {"path": "..\\..\\..\\anaconda3\\envs\\s2n4\\lib\\site-packages\\pymongo\\mongo_client.py", "lineno": 639, "message": "in __init__"}, {"path": "..\\..\\..\\anaconda3\\envs\\s2n4\\lib\\site-packages\\pymongo\\uri_parser.py", "lineno": 470, "message": "in parse_uri"}, {"path": "..\\..\\..\\anaconda3\\envs\\s2n4\\lib\\site-packages\\pymongo\\uri_parser.py", "lineno": 65, "message": "InvalidURI"}], "longrepr": "@pytest.fixture(scope='module')\n    def connection():\n>       conn = MongoClient(MONGO_URI)\n\ntests\\Part_5\\conftest.py:7: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\..\\..\\anaconda3\\envs\\s2n4\\lib\\site-packages\\pymongo\\mongo_client.py:639: in __init__\n    res = uri_parser.parse_uri(\n..\\..\\..\\anaconda3\\envs\\s2n4\\lib\\site-packages\\pymongo\\uri_parser.py:470: in parse_uri\n    user, passwd = parse_userinfo(userinfo)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nuserinfo = ':'\n\n    def parse_userinfo(userinfo):\n        \"\"\"Validates the format of user information in a MongoDB URI.\n        Reserved characters like ':', '/', '+' and '@' must be escaped\n        following RFC 3986.\n    \n        Returns a 2-tuple containing the unescaped username followed\n        by the unescaped password.\n    \n        :Paramaters:\n            - `userinfo`: A string of the form <username>:<password>\n    \n        .. versionchanged:: 2.2\n           Now uses `urllib.unquote_plus` so `+` characters must be escaped.\n        \"\"\"\n        if '@' in userinfo or userinfo.count(':') > 1:\n            if PY3:\n                quote_fn = \"urllib.parse.quote_plus\"\n            else:\n                quote_fn = \"urllib.quote_plus\"\n            raise InvalidURI(\"Username and password must be escaped according to \"\n                             \"RFC 3986, use %s().\" % quote_fn)\n        user, _, passwd = userinfo.partition(\":\")\n        # No password is expected with GSSAPI authentication.\n        if not user:\n>           raise InvalidURI(\"The empty string is not valid username.\")\nE           pymongo.errors.InvalidURI: The empty string is not valid username.\n\n..\\..\\..\\anaconda3\\envs\\s2n4\\lib\\site-packages\\pymongo\\uri_parser.py:65: InvalidURI"}, "teardown": {"duration": 0.0003294000000000352, "outcome": "passed"}}, {"nodeid": "tests/Part_5/Part_5.py::test_data_format", "lineno": 17, "outcome": "error", "keywords": ["Part_5.py", "test_data_format", "tests/Part_5/__init__.py", "ds-sa-nosql"], "setup": {"duration": 0.00025289999999955626, "outcome": "failed", "crash": {"path": "C:\\Users\\Coke\\anaconda3\\envs\\s2n4\\lib\\site-packages\\pymongo\\uri_parser.py", "lineno": 65, "message": "pymongo.errors.InvalidURI: The empty string is not valid username."}, "traceback": [{"path": "tests\\Part_5\\conftest.py", "lineno": 7, "message": ""}, {"path": "..\\..\\..\\anaconda3\\envs\\s2n4\\lib\\site-packages\\pymongo\\mongo_client.py", "lineno": 639, "message": "in __init__"}, {"path": "..\\..\\..\\anaconda3\\envs\\s2n4\\lib\\site-packages\\pymongo\\uri_parser.py", "lineno": 470, "message": "in parse_uri"}, {"path": "..\\..\\..\\anaconda3\\envs\\s2n4\\lib\\site-packages\\pymongo\\uri_parser.py", "lineno": 65, "message": "InvalidURI"}], "longrepr": "@pytest.fixture(scope='module')\n    def connection():\n>       conn = MongoClient(MONGO_URI)\n\ntests\\Part_5\\conftest.py:7: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\..\\..\\anaconda3\\envs\\s2n4\\lib\\site-packages\\pymongo\\mongo_client.py:639: in __init__\n    res = uri_parser.parse_uri(\n..\\..\\..\\anaconda3\\envs\\s2n4\\lib\\site-packages\\pymongo\\uri_parser.py:470: in parse_uri\n    user, passwd = parse_userinfo(userinfo)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nuserinfo = ':'\n\n    def parse_userinfo(userinfo):\n        \"\"\"Validates the format of user information in a MongoDB URI.\n        Reserved characters like ':', '/', '+' and '@' must be escaped\n        following RFC 3986.\n    \n        Returns a 2-tuple containing the unescaped username followed\n        by the unescaped password.\n    \n        :Paramaters:\n            - `userinfo`: A string of the form <username>:<password>\n    \n        .. versionchanged:: 2.2\n           Now uses `urllib.unquote_plus` so `+` characters must be escaped.\n        \"\"\"\n        if '@' in userinfo or userinfo.count(':') > 1:\n            if PY3:\n                quote_fn = \"urllib.parse.quote_plus\"\n            else:\n                quote_fn = \"urllib.quote_plus\"\n            raise InvalidURI(\"Username and password must be escaped according to \"\n                             \"RFC 3986, use %s().\" % quote_fn)\n        user, _, passwd = userinfo.partition(\":\")\n        # No password is expected with GSSAPI authentication.\n        if not user:\n>           raise InvalidURI(\"The empty string is not valid username.\")\nE           pymongo.errors.InvalidURI: The empty string is not valid username.\n\n..\\..\\..\\anaconda3\\envs\\s2n4\\lib\\site-packages\\pymongo\\uri_parser.py:65: InvalidURI"}, "teardown": {"duration": 0.0004157000000004629, "outcome": "passed"}}], "warnings": [{"message": "please use dns.resolver.resolve() instead", "category": "DeprecationWarning", "when": "collect", "filename": "C:\\Users\\Coke\\anaconda3\\envs\\s2n4\\lib\\site-packages\\pymongo\\srv_resolver.py", "lineno": 72}, {"message": "please use dns.resolver.resolve() instead", "category": "DeprecationWarning", "when": "collect", "filename": "C:\\Users\\Coke\\anaconda3\\envs\\s2n4\\lib\\site-packages\\pymongo\\srv_resolver.py", "lineno": 57}, {"message": "please use dns.resolver.resolve() instead", "category": "DeprecationWarning", "when": "collect", "filename": "C:\\Users\\Coke\\anaconda3\\envs\\s2n4\\lib\\site-packages\\pymongo\\srv_resolver.py", "lineno": 72}, {"message": "please use dns.resolver.resolve() instead", "category": "DeprecationWarning", "when": "collect", "filename": "C:\\Users\\Coke\\anaconda3\\envs\\s2n4\\lib\\site-packages\\pymongo\\srv_resolver.py", "lineno": 57}, {"message": "please use dns.resolver.resolve() instead", "category": "DeprecationWarning", "when": "collect", "filename": "C:\\Users\\Coke\\anaconda3\\envs\\s2n4\\lib\\site-packages\\pymongo\\srv_resolver.py", "lineno": 72}, {"message": "please use dns.resolver.resolve() instead", "category": "DeprecationWarning", "when": "collect", "filename": "C:\\Users\\Coke\\anaconda3\\envs\\s2n4\\lib\\site-packages\\pymongo\\srv_resolver.py", "lineno": 57}, {"message": "please use dns.resolver.resolve() instead", "category": "DeprecationWarning", "when": "runtest", "filename": "C:\\Users\\Coke\\anaconda3\\envs\\s2n4\\lib\\site-packages\\pymongo\\srv_resolver.py", "lineno": 72}, {"message": "please use dns.resolver.resolve() instead", "category": "DeprecationWarning", "when": "runtest", "filename": "C:\\Users\\Coke\\anaconda3\\envs\\s2n4\\lib\\site-packages\\pymongo\\srv_resolver.py", "lineno": 57}, {"message": "please use dns.resolver.resolve() instead", "category": "DeprecationWarning", "when": "runtest", "filename": "C:\\Users\\Coke\\anaconda3\\envs\\s2n4\\lib\\site-packages\\pymongo\\srv_resolver.py", "lineno": 72}, {"message": "please use dns.resolver.resolve() instead", "category": "DeprecationWarning", "when": "runtest", "filename": "C:\\Users\\Coke\\anaconda3\\envs\\s2n4\\lib\\site-packages\\pymongo\\srv_resolver.py", "lineno": 57}]}